all: ArrStack ListStack

ArrStack:
	g++ ./Array/lab_array.cpp ./Array/ArrStack_functions.cpp -o ./Array/ArrStack

ListStack:
	g++ ./List/lab_list.cpp ./List/ListStack_functions.cpp  -o ./List/ListStack