#!/bin/bash

very_small_tests="very_small_tests"
small_tests="small_tests"./
big_tests="big_tests"
dub_tests="tests_most_duplicates"

k=5
max_rand=10000

from=0
to=1000000
step=10000

dir_name=dub_tests
mkdir $dir_name

for ((i=from; i<=to; i+=step))
do
for ((j=0; j<k; j++))
do
./arr_generation $i $max_rand $RANDOM > ./$dir_name/${i}_${j}.in
./arr_sorting < ./$dir_name/${i}_${j}.in > ./$dir_name/${i}_${j}.out
done
done
